sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 3LKL2tkKzC1GpVFPhwR8NyGgtnccRkPhucesEiMooYdOBaAu0EwJc6d7YFEmEWbneY2MyVlKifja7FYf0uwWwYZe2JqPxHjTHY8l6vv/fqp6m39Oa6vE8T2YUBP8Rgh6aFpQtyjckJVJy5YWyK5E8eMo+c/UzfaUfg25Vdj+VDM9oqhN5rcdX29djvxr6vtrCllcRVwnlMA7ZvemG3DcA3Qu//lS6lo/AT8xmH/YEfOh72Kj1k90ThM4edl6DU0fhsV8Iz6wD9814vWE7NmdDWDyfGAt3kY6amUaU2IX+XRZgbpi6NZjyoMr1vP8d8zyBtw9/1tfJ4LPY0gKzNdkLNeQMJCbMqWdcB5vI714WUhGLROISpPpx0jEtztNpHkytTWWjJit/Qsr1tTZ8GRQtDXwzCFKH4VSPX92/Ex85DQOPB3To1Eytq20juXqJpXqJesQWXz29dZ/9pAXO2Y8lrd1XNk1AfNUbh4qZ1xQoEU/wzaEarfq3VmS5bvLHyAU/yerl2yg9lMIre5pPL3hYBVVqjuAWAc7T83nSIaXFFYj6+BIm/Xz40W6ONVvCLnfdCef3A4eFqLa/XWuDpoZWG9TMlhx8v+0LnQY66W39xuCNk5zq66ayVfW+JrHKjHPwelg+I6hlKz0MW3ah36kIZJUL8xVdScbKM0RLsIH66o=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Phyllis-of-Philistia_2155
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy